PACKAGE_NAME="mi-tm1806-led"
PACKAGE_VERSION="0.1"

BUILT_MODULE_NAME[0]="mi-tm1806-led"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"

AUTOINSTALL="yes"
